#workflow.yaml
name: Deploy CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy
        shell: bash
        run: curl wemakeinter.net/deploy.php
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
