#workflow.yaml
name: Deploy CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy
        shell: bash
        run: curl -X POST --data "key=$DEPLOY_SECRET" dev.wemakeinter.net/deploy.php
        env:
          DEPLOY_SECRET: ${{secrets.DEPLOY_SECRET}}
